#############################################
# Usage
#############################################

# Add as a pre-commit hook with Git Defender: git defender --precommit_tool_setup

# Pre-reqs:
## Install pre-commit
# brew install pre-commit

## Install tflint and tfsec

# brew install tfsec
# brew install tflint

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate

#############################################
# Generic hooks
#############################################

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    # -   id: check-added-large-files
    -   id: check-ast
    -   id: fix-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: debug-statements
    -   id: detect-private-key
    -   id: detect-aws-credentials
    -   id: mixed-line-ending
        args: [ '--fix=auto' ]

#############################################
# Terraform specific hooks
#############################################

-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
    - id: terraform-fmt
    - id: terraform-validate
    - id: tflint
      args:
        - "--module"
        - "--config=.tflint.hcl"

#-   repo: https://github.com/antonbabenko/pre-commit-terraform
#    rev: v1.74.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
#    hooks:
#    - id: terraform_tfsec
#    - id: terraform_fmt
#      args:
#        - --args=-diff
#        - --args=-write=true
#        - --args=-recursive
#    - id: terraform_checkov
#      args:
#        - --args=-s

-   repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
    - id: terraform-docs-go
      args: ["--output-file", "README-infrastructure.md"]


#############################################
# Python specific hooks
#############################################

-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
      - id: black
        stages: [commit]
        language_version: python3.11
        additional_dependencies: ['click==8.0.4']  # Why: https://github.com/psf/black/issues/2964
        args: [--config=etl_lambda/pyproject.toml]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        stages: [commit]
        args: [--sp=etl_lambda/pyproject.toml]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        args: [ --config=etl_lambda/pyproject.toml ]
        additional_dependencies: ['types-requests']

-   repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        # Why: https://github.com/PyCQA/pycodestyle/issues/373
        args: [--config, etl_lambda/pyproject.toml, --extend-ignore, E203]

-   repo: local
    hooks:
        # Why: https://pylint.pycqa.org/en/stable/user_guide/installation/pre-commit-integration.html
      - id: pylint
        stages: [commit]
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          ["--rcfile=etl_lambda/pyproject.toml"]
