formatter: markdown table

settings:
  anchor: false
  escape: false
  indent: 4

output:
  file: ../../../README-infrastructure.md
  mode: inject
  template: |-
    <!-- BEGIN_SNOWFLAKE_DOCS -->
    {{ .Content }}
    <!-- END_SNOWFLAKE_DOCS -->
